web-ui/Plate/views.py
from flask import Blueprint, render_template, request, send_from_directory
import Plate.queries

# Define the blueprint
plate_bp = Blueprint('plate', __name__, template_folder='templates')

@plate_bp.route('/images/<path:filename>')
def images(filename):
    upload_to = "/home/myuser/data/grabs"
    return send_from_directory(upload_to, filename)

@plate_bp.route('/<plate_str>')
def plate(plate_str: str):

    # Fetch plate history
    rows = Plate.queries.get_plate_results(plate_str)

    return render_template("index.html", current_route=request.path, rows=rows, plate=plate_str)

web-ui/Reports/views.py
from flask import Blueprint, render_template, request

# Define the blueprint
reports_bp = Blueprint('reports', __name__, template_folder='templates')

@reports_bp.route('/')
def browse():
    return render_template("browse.html", current_route=request.path)

web-ui/app.py
#-----------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.
#-----------------------------------------------------------------------------------------

# Setup logging first
import logging.handlers
import logging, sys
from flask import Response, Flask, render_template, request, jsonify # type: ignore
	
# initialize a flask object
app = Flask(__name__)

# Register blueprints
from Reports.views import reports_bp
from Plate.views import plate_bp
app.register_blueprint(reports_bp, url_prefix='/reports')
app.register_blueprint(plate_bp, url_prefix='/plate')


if __name__ == "__main__":
	# Running directly so setup custom logging
	logging.basicConfig(
		level=logging.INFO,
		format="[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s] %(message)s",
		datefmt="%d/%b/%Y %H:%M:%S",
		stream=sys.stdout)
else:
	# Running under gunicorn so use their logger
	gunicorn_logger = logging.getLogger('gunicorn.error')
	rootLogger = logging.getLogger();
	rootLogger.handlers = gunicorn_logger.handlers
	rootLogger.setLevel(gunicorn_logger.level)

# import the necessary packages
import threading, json, os, errno
import redis, requests
from rq import Queue
from datetime import datetime
from PlateProcessor.plate_processor import PlateProcessor
from PlateProcessor.plate_query import PlateQuery
from PlateProcessor.storage import Storage

# initialize the output frame and a lock used to ensure thread-safe
# exchanges of the output frames (useful when multiple browsers/tabs
# are viewing the stream)
output_image = None
output_json = None
lock = threading.Lock()

# Set up Redis connection
redis_url = os.getenv('REDIS_URL', 'redis://redis:6379/0')
redis_conn = redis.Redis.from_url(redis_url)

# Initialize an RQ queue
queue = Queue(connection=redis_conn)

# Create a plate processor which will handle all processing of the plate results
plate_processor = PlateProcessor()
plate_query = PlateQuery()

upload_to = "/home/myuser/data/grabs"

def format_datetime(value, format='%Y-%m-%d %H:%M:%S'):
    dt = datetime.strptime(value, "%Y-%m-%dT%H:%M:%S.%fZ")
    return dt.strftime(format)

app.jinja_env.filters['datetime'] = format_datetime

@app.before_request
def initialize():
    # Ensure our DB is setup before we try and use it
    if not hasattr(app, 'db_initialized'):
        storage = Storage()
        storage.init_db()
        app.db_initialized = True

@app.route('/plate_detected', methods = ['POST'])
def plate_detected():
	# grab global references
	global output_image, output_json, lock

	resp = Response("OK", 200)
	resp.headers['Content-type'] = 'text/html'

	# Files exist for multipart/form-data
	files = request.files
	if files:
		app.logger.debug("Request contains image")
		app.logger.debug(f"files: {files}")

		# Get the JSON data as we need it to know upload location		
		form = request.form
		json_str = form['json']
		json_data = json.loads(json_str)

		# Ensure our dir exists
		folder_path = os.path.dirname(json_data['data']['filename'])
		filename = os.path.basename(json_data['data']['filename'])
		upload_dir = os.path.join(upload_to, folder_path)
		if not os.path.exists(upload_dir):
			try:
				os.makedirs(upload_dir)
			except OSError as exc:  # Guard against race condition
				if exc.errno != errno.EEXIST:
					raise

		for key in files.keys():  # The file doesn't exist under upload
			app.logger.debug(f"key: {key}")
			f = files[key]

			# Read the file content into bytes before saving
			file_content = f.read()
			file_path = os.path.join(upload_dir, filename)
			with open(file_path, 'wb') as file:
				file.write(file_content)

			# wait until the lock is acquired
			with lock:
				output_image = file_content
			break
	else:
		app.logger.debug("Request contains json")
		try:
			json_str = request.form.get('json')
			json_data = json.loads(json_str)
		except json.JSONDecodeError as e:
			app.logger.exception("Unable to decode json from payload")
			json_data = {}

	# wait until the lock is acquired
	with lock:
		output_json = json_data

	# Hand over now to our processor to do further work on this result
	app.logger.info(f"json_data: {json_data}")
	queue.enqueue(plate_processor.process, json_str)

	return resp

@app.route("/")
def home():
	# return the rendered template
	return render_template("home.html", current_route=request.path)

@app.route("/data")
def data():
	# grab global references
	global output_json, lock

    # wait until the lock is acquired
	with lock:
		return jsonify(output_json)

def generate_capture():
	# grab global references
	global output_image, lock
	
	# loop over frames from the output stream
	while True:
		# wait until the lock is acquired
		with lock:
			# check if the output frame is available, otherwise skip
			# the iteration of the loop
			if output_image is None:
				continue
			
			# yield the output frame in the byte format
			yield(b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + 
				bytearray(output_image) + b'\r\n')

@app.route("/capture")
def capture():
	# return the response generated along with the specific media
	# type (mime type)
	return Response(generate_capture(),
		mimetype = "multipart/x-mixed-replace; boundary=frame")

@app.route('/last_10_plates')
def last_10_plates():
	data = plate_query.get_latest_plates(10)
	return render_template('last_10_plates.html', rows=data)

@app.route('/plate_counts')
def plate_counts():
	data = plate_query.get_direction_plate_count()
	return render_template('plate_counts.html', rows=data)

@app.route('/weight_counts')
def weight_counts():
	data = plate_query.get_plates_by_weight()
	return render_template('plate_counts.html', rows=data)

# Used for starting locally. Under gunircorn this won't get hit
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True, threaded=True, use_reloader=False)

web-ui/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DVLA HGV Check</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="static/styles.css">
    {% block script %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <span class="navbar-brand">DVLA HGV Check</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
                {% with route_name='home', link_text='Home' %}{% include 'nav_link.html' %}{% endwith %}
            </li>
            <li class="nav-item">
                {% with route_name='reports.browse', link_text='Reports' %}{% include 'nav_link.html' %}{% endwith %}
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container my-5">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="main.js"></script>
    <script src="https://unpkg.com/htmx.org@2.0.1" integrity="sha384-QWGpdj554B4ETpJJC9z+ZHJcA/i59TyjxEPXiiUgN2WmTyV5OEZWCD6gQhgkdpB/" crossorigin="anonymous"></script>
  </body>
</html>

web-ui/templates/home.html
{% extends "base.html" %}

{% block script %}
<script>
  function fetchData() {
      fetch('/data')
          .then(response => response.json())
          .then(data => {
              document.getElementById('json-data').textContent = JSON.stringify(data, null, 2);
          })
          .catch(error => console.error('Error fetching data:', error));
  }

  function imageLoaded() {
      fetchData();  // Fetch data when the image loads

      // Update the image src to force reload (add a unique parameter to prevent caching)
      var img = document.getElementById('dynamic-image');
      img.src = '/capture?' + new Date().getTime();
  }

  // Initial load
  document.addEventListener('DOMContentLoaded', function() {
      imageLoaded();
  });

  // Periodically change the image every 5 seconds to simulate updates
  setInterval(function() {
      var img = document.getElementById('dynamic-image');
      img.src = '/capture?' + new Date().getTime();
  }, 5000);
</script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-8">
      <img id="dynamic-image" class="img-fluid" src="{{ url_for('capture') }}"  onload="imageLoaded()"/>
  </div>
  <div class="col-md-4">
    <div class="row pb-3">
      <table class="table table-sm">
        <thead>
          <th>Direction</th>
          <th>Today</th>
          <th>Week</th>
          <th>Month</th>
          <th>Year</th>
        </thead>
        <tbody hx-get="/plate_counts" hx-trigger="load, every 30s" hx-target="this">
            <!-- Table rows will be injected here -->
        </tbody>
      </table>
    </div>
    <div class="row pb-3">
      <table class="table table-sm">
        <thead>
          <th>Weight</th>
          <th>Today</th>
          <th>Week</th>
          <th>Month</th>
          <th>Year</th>
        </thead>
        <tbody hx-get="/weight_counts" hx-trigger="load, every 30s" hx-target="this">
            <!-- Table rows will be injected here -->
        </tbody>
      </table>
    </div>
    <div class="row">
      <table class="table table-sm">
        <thead>
          <th>Time</th>
          <th>Plate</th>
          <th>Class</th>
          <th>Make</th>
          <th>Weight</th>
        </thead>
        <tbody hx-get="/last_10_plates" hx-trigger="load, every 30s" hx-target="this">
            <!-- Table rows will be injected here -->
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

web-ui/templates/last_10_plates.html
{% for row in rows %}
<tr {% if row[4] >= 7500 %}class="table-danger"{% endif %}>
    <td>{{ row[0] | datetime('%H:%M:%S') }}</td>
    <td><a href="{{ url_for('plate.plate', plate_str=row[1]) }}">{{ row[1] }}</a></td>
    <td>{{ row[2] }}</td>
    <td>{{ row[3] }}</td>
    <td>{{ row[4] }}</td>
</tr>
{% endfor %}

web-ui/templates/nav_link.html
<a class="nav-link {% if current_route == url_for(route_name) %}active{% endif %}" href="{{ url_for(route_name) }}">{{ link_text }}</a>

web-ui/templates/plate_counts.html
{% for row in rows %}
<tr>
    <td>{{ row[0] }}</td>
    <td>{{ row[1] }}</td>
    <td>{{ row[2] }}</td>
    <td>{{ row[3] }}</td>
    <td>{{ row[4] }}</td>
</tr>
{% endfor %}